version: '3.8'

services:
  mariadb:
    container_name: mariadb_app
    build: 
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb
    
    env_file:
      - ./.env
    
    networks:
      - inception_network
    
    volumes:
      - mariadb_data:/var/lib/mysql
    
    restart: always
    
  wp_php:
    container_name: wp_php_app
    build: 
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    image: wp_php

    env_file:
      - ./.env

    networks:
      - inception_network
    
    volumes:
      - wordpress_data:/var/www/html 

    depends_on:
      - mariadb

    restart: always
  nginx:
    container_name: nginx_app
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    image: nginx
    
    env_file:
      - ./.env
    
    ports:
      - 443:443
    
    networks:
      - inception_network
    
    volumes:
      - wordpress_data:/var/www/html

    depends_on:
      - wp_php
      - mariadb

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/data/wordpress_data
      o: bind

networks:
  inception_network:
    driver: bridge