version: '3.8'

services:
  mariadb:
    build: 
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile

    env_file:
      - ./.env
    
    volumes:
      - /home/admin/data/mariadb_data:/var/lib/mysql
    
    ports:
      - 3306:3306
    
  # nginx:
  # wp_php: