version: '3.8'

services:
  mariadb:
    container_name: mariadb_app
    build: 
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    image: mariadb
    pull_policy: never
    
    env_file:
      - ./.env
    
    networks:
      - inception_network
    
    volumes:
      - mariadb_data:/var/lib/mysql
    
    restart: always
    
  wp_php:
    container_name: wp_php_app
    build: 
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    image: wp_php
    pull_policy: never

    env_file:
      - ./.env

    networks:
      - inception_network
    
    volumes:
      - wordpress_data:/var/www/html 

    depends_on:
      - mariadb

    restart: always
  nginx:
    container_name: nginx_app
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    image: nginx
    pull_policy: never
    
    env_file:
      - ./.env
    
    ports:
      - 443:443
    
    networks:
      - inception_network
    
    volumes:
      - wordpress_data:/var/www/html

    depends_on:
      - wp_php
      - mariadb
  
  redis:
    container_name: redis_app
    build: 
      context: ./requirements/bonus/redis
      dockerfile: ./Dockerfile
    image: redis
    pull_policy: never

    env_file:
      - ./.env

    networks:
      - inception_network

    volumes:
      - /data

    depends_on:
      - wp_php

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress_data
      o: bind

networks:
  inception_network:
    driver: bridge