version: '3.8'

services:
  mariadb:
    container_name: mariadb_app
    build: 
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb
    
    env_file:
      - ./.env
    
    volumes:
      - /home/admin/data/mariadb_data:/var/lib/mysql
    
    ports:
      - 3306:3306
    
    restart: always
    
  wp_php:
    container_name: wp_php_app
    image: wp_php

    build: 
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile

    env_file:
      - ./.env
    
    volumes:
      - /home/admin/data/wordpress_data:/var/www/html 

    depends_on:
      - mariadb

    restart: always
  # nginx:
    # container_name: nginx_app
    # image: nginx
    # depends_on:
    #   - wp_php